name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]

    environment: build
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java }}
        check-latest: true
    - name: Build with Gradle
      run: ./gradlew clean build
      env:
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVENCENTRALUSERNAME }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVENCENTRALPASSWORD }}
        ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.MAVEN_SIGNING_PRIVATE_KEY }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD || '' }}
        REMOTE_CACHE_URL: ${{ secrets.REMOTE_CACHE_URL }}
        REMOTE_CACHE_USER: ${{ secrets.REMOTE_CACHE_USER }}
        REMOTE_CACHE_PASS: ${{ secrets.REMOTE_CACHE_PASS }}
    - uses: actions/upload-artifact@v4
      with:
        name: Package
        path: obd/build/outputs/aar
